# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: banking_service.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'banking_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15\x62\x61nking_service.proto\x12\x07\x62\x61nking\".\n\x14\x41\x63\x63ountStatusRequest\x12\x16\n\x0e\x61\x63\x63ount_number\x18\x01 \x01(\t\"l\n\x15\x41\x63\x63ountStatusResponse\x12\x16\n\x0e\x61\x63\x63ount_number\x18\x01 \x01(\t\x12\x16\n\x0e\x61\x63\x63ount_holder\x18\x02 \x01(\t\x12\x0e\n\x06status\x18\x03 \x01(\t\x12\x13\n\x0b\x64\x61ily_limit\x18\x04 \x01(\x01\"\\\n\x15RiskEvaluationRequest\x12\x16\n\x0e\x61\x63\x63ount_number\x18\x01 \x01(\t\x12\x0e\n\x06\x61mount\x18\x02 \x01(\x01\x12\x1b\n\x13\x64\x65stination_country\x18\x03 \x01(\t\"h\n\x16RiskEvaluationResponse\x12\x15\n\revaluation_id\x18\x01 \x01(\t\x12\x12\n\nrisk_score\x18\x02 \x01(\x05\x12\x13\n\x0bis_approved\x18\x03 \x01(\x08\x12\x0e\n\x06reason\x18\x04 \x01(\t\">\n\x14\x46reezeAccountRequest\x12\x16\n\x0e\x61\x63\x63ount_number\x18\x01 \x01(\t\x12\x0e\n\x06reason\x18\x02 \x01(\t\"U\n\x15\x46reezeAccountResponse\x12\x16\n\x0e\x61\x63\x63ount_number\x18\x01 \x01(\t\x12\x11\n\tis_frozen\x18\x02 \x01(\x08\x12\x11\n\ttimestamp\x18\x03 \x01(\t2\x83\x02\n\rBankingEngine\x12Q\n\x10GetAccountStatus\x12\x1d.banking.AccountStatusRequest\x1a\x1e.banking.AccountStatusResponse\x12O\n\x0c\x45valuateRisk\x12\x1e.banking.RiskEvaluationRequest\x1a\x1f.banking.RiskEvaluationResponse\x12N\n\rFreezeAccount\x12\x1d.banking.FreezeAccountRequest\x1a\x1e.banking.FreezeAccountResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'banking_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ACCOUNTSTATUSREQUEST']._serialized_start=34
  _globals['_ACCOUNTSTATUSREQUEST']._serialized_end=80
  _globals['_ACCOUNTSTATUSRESPONSE']._serialized_start=82
  _globals['_ACCOUNTSTATUSRESPONSE']._serialized_end=190
  _globals['_RISKEVALUATIONREQUEST']._serialized_start=192
  _globals['_RISKEVALUATIONREQUEST']._serialized_end=284
  _globals['_RISKEVALUATIONRESPONSE']._serialized_start=286
  _globals['_RISKEVALUATIONRESPONSE']._serialized_end=390
  _globals['_FREEZEACCOUNTREQUEST']._serialized_start=392
  _globals['_FREEZEACCOUNTREQUEST']._serialized_end=454
  _globals['_FREEZEACCOUNTRESPONSE']._serialized_start=456
  _globals['_FREEZEACCOUNTRESPONSE']._serialized_end=541
  _globals['_BANKINGENGINE']._serialized_start=544
  _globals['_BANKINGENGINE']._serialized_end=803
# @@protoc_insertion_point(module_scope)
