# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import banking_service_pb2 as banking__service__pb2

GRPC_GENERATED_VERSION = '1.83.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in banking_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class BankingEngineStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetAccountStatus = channel.unary_unary(
                '/banking.BankingEngine/GetAccountStatus',
                request_serializer=banking__service__pb2.AccountStatusRequest.SerializeToString,
                response_deserializer=banking__service__pb2.AccountStatusResponse.FromString,
                _registered_method=True)
        self.EvaluateRisk = channel.unary_unary(
                '/banking.BankingEngine/EvaluateRisk',
                request_serializer=banking__service__pb2.RiskEvaluationRequest.SerializeToString,
                response_deserializer=banking__service__pb2.RiskEvaluationResponse.FromString,
                _registered_method=True)
        self.FreezeAccount = channel.unary_unary(
                '/banking.BankingEngine/FreezeAccount',
                request_serializer=banking__service__pb2.FreezeAccountRequest.SerializeToString,
                response_deserializer=banking__service__pb2.FreezeAccountResponse.FromString,
                _registered_method=True)


class BankingEngineServicer:
    """Missing associated documentation comment in .proto file."""

    def GetAccountStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EvaluateRisk(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FreezeAccount(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BankingEngineServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetAccountStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAccountStatus,
                    request_deserializer=banking__service__pb2.AccountStatusRequest.FromString,
                    response_serializer=banking__service__pb2.AccountStatusResponse.SerializeToString,
            ),
            'EvaluateRisk': grpc.unary_unary_rpc_method_handler(
                    servicer.EvaluateRisk,
                    request_deserializer=banking__service__pb2.RiskEvaluationRequest.FromString,
                    response_serializer=banking__service__pb2.RiskEvaluationResponse.SerializeToString,
            ),
            'FreezeAccount': grpc.unary_unary_rpc_method_handler(
                    servicer.FreezeAccount,
                    request_deserializer=banking__service__pb2.FreezeAccountRequest.FromString,
                    response_serializer=banking__service__pb2.FreezeAccountResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'banking.BankingEngine', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('banking.BankingEngine', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class BankingEngine:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetAccountStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/banking.BankingEngine/GetAccountStatus',
            banking__service__pb2.AccountStatusRequest.SerializeToString,
            banking__service__pb2.AccountStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EvaluateRisk(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/banking.BankingEngine/EvaluateRisk',
            banking__service__pb2.RiskEvaluationRequest.SerializeToString,
            banking__service__pb2.RiskEvaluationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def FreezeAccount(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/banking.BankingEngine/FreezeAccount',
            banking__service__pb2.FreezeAccountRequest.SerializeToString,
            banking__service__pb2.FreezeAccountResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
